
services:
  db:
    build: db/.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: world
    ports:
      - "3308:3306"

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: "db:3306"
    stdin_open: true
    tty: true
